project:
  name: connect-integration-ecs-uk-rocketcx
  package_lambda: false
  regions:
    - eu-west-1
    - us-east-1
    - us-east-2
    - ap-south-1
tests:
  connect-integration-ecs-uk-rocketcx:
    parameters:
      AmazonConnectInstanceID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      CallRecordingS3BucketName: ""
      IAMUserName: ""
      ServiceNowHostURL: https://dummyservicenow.service-now.com/
      ServiceNowPassword: dummypassword
      ServiceNowUserName: dummy.user
    regions:
      - us-east-1
      - eu-west-1
      - us-east-1
      - us-east-2
      - ap-south-1
    template: templates/rocketcx.template.yaml
