project:
  name: connect-integration-ecs-uk-rocketcx
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
tests:
  connect-integration-ecs-uk-rocketcx:
    parameters:
      AmazonConnectInstanceID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      CallRecordingS3BucketName: ''
      IAMUserName: ''
      ServiceNowHostURL: https://dummyservicenow.service-now.com/
      ServiceNowPassword: dummypassword
      ServiceNowUserName: dummy.user
    regions:
      - us-east-1
    template: templates/rocketcx-cloudformation.yml
